module.exports = {
    externals: {
        assert: 'commonjs assert',
        child_process: 'commonjs child_process',
        constants: 'commonjs constants',
        crypto: 'commonjs crypto',
        electron: 'commonjs electron',
        fs: 'commonjs fs',
        http: 'commonjs http',
        https: 'commonjs https',
        ipc: 'commonjs ipc',
        net: 'commonjs net',
        os: 'commonjs os',
        path: 'commonjs path',
        querystring: 'commonjs querystring',
        remote: 'commonjs remote',
        stream: 'commonjs stream',
        tls: 'commonjs tls',
        url: 'commonjs url',
        util: 'commonjs util',
        zlib: 'commonjs zlib',
    },
};
