module.exports = {
    target: ['electron-renderer', 'es2015'],
    externals: {
        '@electron/remote': 'commonjs @electron/remote',
        electron: 'commonjs electron',
        child_process: 'commonjs child_process',
        ipc: 'commonjs ipc',
        'ipc-renderer': 'commonjs ipc-renderer',
        remote: 'commonjs remote',
        fs: 'commonjs fs',
        assert: 'commonjs assert',
        crypto: 'commonjs crypto',
        http: 'commonjs http',
        https: 'commonjs https',
        'fs-extra': 'commonjs fs-extra',
        ffbinaries: 'commonjs ffbinaries',
        'extract-zip': 'commonjs extract-zip',
        yauzl: 'commonjs yauzl',
        'node-downloader-helper': 'commonjs node-downloader-helper',
        'command-exists-promise': 'commonjs command-exists-promise',
        os: 'commonjs os',
        path: 'commonjs path',
        readline: 'commonjs readline',
        stream: 'commonjs stream',
        timers: 'commonjs timers',
        util: 'commonjs util',
        constants: 'commonjs constants',
        net: 'commonjs net',
        querystring: 'commonjs querystring',
        url: 'commonjs url',
    },
};