name: Nightly builds
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
    nightly_build_on_linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '14.x'
            - name: install rpm and libarchive
              run: sudo apt install rpm libarchive-tools
            - name: install dependencies
              run: npm install
            - name: run unit tests
              run: npm run test
            - name: build
              run: npm run electron:linux
            - name: fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - name: uploading rpm artifact
              uses: actions/upload-artifact@v2
              with:
                  name: vitomu-nightly-rpm
                  path: release/Vitomu-${{ steps.ver_name.outputs.prop }}.rpm
            - name: upload deb artifact
              uses: actions/upload-artifact@v2
              with:
                  name: vitomu-nightly-deb
                  path: release/Vitomu-${{ steps.ver_name.outputs.prop }}.deb
            - name: upload appimage artifact
              uses: actions/upload-artifact@v2
              with:
                  name: vitomu-nightly-appimage
                  path: release/Vitomu-${{ steps.ver_name.outputs.prop }}.AppImage
            - name: upload snap artifact
              uses: actions/upload-artifact@v2
              with:
                  name: vitomu-nightly-snap
                  path: release/Vitomu-${{ steps.ver_name.outputs.prop }}.snap
            - name: upload pacman artifact
              uses: actions/upload-artifact@v2
              with:
                  name: vitomu-nightly-pacman
                  path: release/Vitomu-${{ steps.ver_name.outputs.prop }}.pacman

    nightly_build_on_mac:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '14.x'
            - name: install dependencies
              run: npm install
            - name: run unit tests
              run: npm run test
            - name: build
              run: npm run electron:mac
            - name: fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - name: upload build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: vitomu-nightly-macos
                  path: release/Vitomu-${{ steps.ver_name.outputs.prop }}.dmg

    nightly_build_on_win:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '14.x'
            - name: install dependencies
              run: npm install
            - name: run unit tests
              run: npm run test
            - name: build
              run: npm run electron:windows
            - name: fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - name: upload build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: vitomu-nightly-win
                  path: release\Vitomu-${{ steps.ver_name.outputs.prop }}.exe
